<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="iDeliver8" name="com.testing.Testng_ft" tests="1" failures="0" timestamp="12 Feb 2018 11:35:54 GMT" time="0.002" errors="1">
  <testcase name="test" time="0.002" classname="com.testing.Testng_ft">
    <error type="com.hp.lft.sdk.GeneralLeanFtException" message="An Internal problem has occurred, please make sure the LeanFT sdk was properly initialized.">
      <![CDATA[com.hp.lft.sdk.GeneralLeanFtException: An Internal problem has occurred, please make sure the LeanFT sdk was properly initialized.
	at com.hp.lft.sdk.internal.CommunicationClientImpl.send(CommunicationClientImpl.java:76)
	at com.hp.lft.sdk.web.BrowserFactory$BrowserFactoryInstance$1.invoke(BrowserFactory.java:122)
	at com.hp.lft.sdk.web.BrowserFactory$BrowserFactoryInstance$1.invoke(BrowserFactory.java:115)
	at com.hp.lft.sdk.internal.TestObjectOperationWrapper.executeWithEvents(TestObjectOperationWrapper.java:120)
	at com.hp.lft.sdk.internal.TestObjectOperationWrapper.executeWithEvents(TestObjectOperationWrapper.java:97)
	at com.hp.lft.sdk.web.BrowserFactory$BrowserFactoryInstance.launch(BrowserFactory.java:128)
	at com.hp.lft.sdk.web.BrowserFactory.launch(BrowserFactory.java:43)
	at com.testing.Testng_ft.run(Testng_ft.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.TestRunner.beforeRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:616)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- test -->
</testsuite> <!-- com.testing.Testng_ft -->
